# Generated by Django 3.1.7 on 2021-07-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
